# Generated by Django 4.1.1 on 2022-10-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackForm',
            new_name='Feedback',
        ),
    ]
