# Generated by Django 4.1.1 on 2023-04-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
