# Generated by Django 4.1.1 on 2023-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_feedback_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='Things to be improved', max_length=40),
            preserve_default=False,
        ),
    ]
